name: check_pr
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
    - main
    - develop
    - release/*
jobs:
  docker-action-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - shell: bash
      env:
          BRANCH_NAME: ${{github.head_ref}}
      run: COMMAND="echo X${BRANCH_NAME}Y" docker run ubuntu bash -c "${COMMAND}"
