name: check_pr
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
    - main
    - develop
    - release/*
jobs:
  docker-action-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - env:
          BRANCH_NAME: ${{github.head_ref}}
      run: docker run ubuntu bash -c "echo ${BRANCH_NAME}"
