name: deploy
on:
  push:
    branches:
    - main
    - release/*
jobs:
  docker-action-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: 'echo "Hello" >| output.txt'
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.MY_SECRET_NAME }}
        run: echo "${SUPER_SECRET}" > output.txt
      - run: 'cat output.txt'
      - run: 'ls -al'
      - run: 'docker-compose up --build'
      - run: 'cat output.txt'
      - run: 'cat README.md'
    

