name: deploy
on:
  push:
    branches:
    - main
    - release/*
jobs:
  docker-action-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ': >| output.txt && docker-compose up --build'
      - run: 'cat output.txt'
      - run: 'cat README.md'

